input_data_path: "data/raw/train.csv"
output_model_path: "models/model.pkl"
output_metric_path: "models/metrics.json"
val_size: 0.2
training_params:
  loss: 'deviance'
  learning_rate: 0.05
  n_estimators: 200
feature_params:
  deleted_features: ['fbs']
  target_column: 'condition'
  normalize_features: ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
